remote_theme: pmarsceill/just-the-docs

color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "Home":
    - "http://www.theagencywiki.org/"
  "About":
    - "http://make.theagencywiki.org/"
  "Contribute":
    - "https://make.theagencywiki.org/CONTRIBUTING.html"
