remote_theme: pmarsceill/just-the-docs

color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "About":
    - "https://ccarfi.github.io/the-agency-wiki-v1/"
  "Contribute":
    - "https://ccarfi.github.io/the-agency-wiki-v1/CONTRIBUTING.html"
