color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "Home":
    - "https://www.theagencywiki.org/"
  "About":
    - "https://make.theagencywiki.org/"
  "Contribute":
    - "https://make.theagencywiki.org/CONTRIBUTING.html"
